global:
  sendAnonymousUsage: true

accesslog: true
log:
  level: INFO
  format: common

api:
  dashboard: true

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443'
    asDefault: true

providers:
  file:
    filename: /etc/traefik/config.yaml
    watch: true
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    watch: true
