log:
  level: ERROR
  format: common

certificatesresolvers:
  letsencrypt:
    acme:
      tlschallenge: true
      email: letsencrypt@example.org
      storage: /etc/traefik/letsencrypt/acme.json

entryPoints:
  http:
    address: ':80'
    http:
      redirections:
        entrypoint:
          to: https
          scheme: https
  https:
    address: ':443'
    asDefault: true
    http:
      tls:
        certresolver: letsencrypt

providers:
  file:
    filname: /etc/traefik/config.yaml
    watch: true
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false
    watch: true
